[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[general]
import = [
"~/.config/alacritty/themes/e-ink-dark.toml"
]

[[hints.enabled]]
command = "qutebrowser"
hyperlinks = true
post_processing = true
persist = false
mouse = { enabled = true }
binding = { key = "U", mods = "Control|Shift" }
regex = '(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^<>"\s{-}^`]+'

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0
