[[language]]
name = "rust"

[language.config.check]
command = "clippy"

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
# auto-format = false
formatter = { command = "prettier", args = ["--parser", "typescript"]}

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$"
file-types = ["tsx"]
# auto-format = false
formatter = { command = "prettier", args = ["--parser", "typescript"]}
